//RECIBE CADA TABLA DE DATOS
//TABLA DE COMERCIOS

GET http://localhost:3000/api/comercio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ3NWQ1NzQwODY5NTZiYTI5ZDVjNjkiLCJpYXQiOjE3MTU5NTI5ODMsImV4cCI6MTcxNTk2MDE4M30.IlAH5qWzX4rNJa0D4r5nwXI6cUQi9RNA95mEge6ELRY
###
DELETE http://localhost:3000/api/comercio/664cc0a78160ee71f092990f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE
###
//TABLA DE COMERCIOS CON ID
GET http://localhost:3000/api/comercio/664753864890cd274155d413
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE
###
POST http://localhost:3000/api/comercio
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRjY2VhNDliODFmNWMxNmQ1YjdhM2YiLCJpYXQiOjE3MTYzMDk2NjgsImV4cCI6MTcxNjMxNjg2OH0.YyFK3-pxt4UA8dsj2cIaQkmU7Up3EfjK9Kq72Imubhg

{
  "nombre": "MiCcio2",
  "password":"1231213132",
  "CIF": "A155880113556",
  "direccion": "Calle Ejemplo, 123",
  "email": "cd@empe.com",
  "telefono": "123456789"
}
###


//COMERCIO TOKEN EDITADO

PUT http://localhost:3000/api/comercio/664753864890cd274155d413
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ3NTM4NjQ4OTBjZDI3NDE1NWQ0MTMiLCJpYXQiOjE3MTU5NTA0QzAsImV4cCI6MTcxNTk1NzY3MH0.IWoR4kLsQGxafw784RWjlR9-Mi7UEty_9ZGlF3jKLOE

{
  "nombre": "MiCcio2",
  "password":"1231213132",
  "CIF": "A150003556",
  "direccion": "Calle Ejemplo, 123",
  "email": "codd@emle.com",
  "telefono": "123456789"
}
###

//ELIMINAR ADMINS DELETE

