//RECIBE CADA TABLA DE DATOS
//TABLA DE COMERCIOS

GET http://localhost:3000/api/comercio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ3NWQ1NzQwODY5NTZiYTI5ZDVjNjkiLCJpYXQiOjE3MTU5NTI5ODMsImV4cCI6MTcxNTk2MDE4M30.IlAH5qWzX4rNJa0D4r5nwXI6cUQi9RNA95mEge6ELRY
###
DELETE http://localhost:3000/api/comercio/664dc42ef0933dd6ef7fc0a8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE
###
//TABLA DE COMERCIOS CON ID
GET http://localhost:3000/api/comercio/664753864890cd274155d413
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE
###
POST http://localhost:3000/api/comercio
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRkYzRmZjA1Zjk0YTBkM2E4YzQ5OTgiLCJpYXQiOjE3MTYzNzI3MzUsImV4cCI6MTcxNjM3OTkzNX0.MVelrCOp3TYCxyUTKhcHOiunN0myTbrnHQ9bhQAhmSs

{
  "nombre": "MiCcio2",
  "password":"1231213132",
  "CIF": "A335881113556",
  "direccion": "Calle Ejemplo, 123",
  "email": "cd@qdadae.com",
  "telefono": "123456789"
}
###


//COMERCIO TOKEN EDITADO

PUT http://localhost:3000/api/comercio/664dc5ab05f94a0d3a8c49ab
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRkYzVhYjA1Zjk0YTBkM2E4YzQ5YWIiLCJpYXQiOjE3MTYzNzI5MDgsImV4cCI6MTcxNjM4MDEwOH0.vT3bb-0tCqd7ea2laXgyulcu66VwdhIo029IcT_GjDo

{
  "nombre": "MiCcio2",
  "password":"1231213132",
  "CIF": "A150112556",
  "direccion": "Calle Ejemplo, 123",
  "email": "coeeeed@emle.com",
  "telefono": "123456789"
}
###

//ELIMINAR ADMINS DELETE

