//RECIBE CADA TABLA DE DATOS
//TABLA DE COMERCIOS

GET http://localhost:3000/api/comercio
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE
###

//TABLA DE COMERCIOS CON ID
GET http://localhost:3000/api/comercio/663a0232b103fc9c69821e2b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE
###
POST http://localhost:3000/api/comercio
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE

{
  "nombre": "Mi Comercio2",
  "password":"123123132",
  "CIF": "A183877266",
  "direccion": "Calle Ejemplo, 123",
  "email": "com@example.com",
  "telefono": "123456789"
}
###


//COMERCIO TOKEN EDITADO

PUT http://localhost:3000/api/comercio/663a0232b103fc9c69821e2b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjNhMDIzMmIxMDNmYzljNjk4MjFlMmIiLCJpYXQiOjE3MTU2ODIzMzYsImV4cCI6MTcxNTY4OTUzNn0.9M7Fo3kXfvM4CUeaR3uDp-dpxNniMR83vggmmbsFaMk

{
  "nombre": "Nuevo nombre",
  "email": "nuevo@example.com",
  "password": "nuevacontraseña",
  "edad": 31,
  "ciudad": "Nueva Ciudad",
  "intereses": ["música", "viajes"],
  "permiteRecibirOfertas": false
}
###

//ELIMINAR ADMINS DELETE

DELETE http://localhost:3000/api/comercio/662a309d777a76a05dba6421
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE
