GET http://localhost:3000/api/control
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE
###

GET http://localhost:3000/api/control/664dadd16aa7066f6d6bcf2e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE
###

DELETE http://localhost:3000/api/control/664dc4e205f94a0d3a8c4991
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE
###                                        //DElete
GET http://localhost:3000/api/control/ciudad/Barcelona
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE
###

GET http://localhost:3000/api/control/intereses/Padel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE
###

GET http://localhost:3000/api/control/rol/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE
###

//MIEMBRO

POST http://localhost:3000/api/control/register
Content-Type: application/json

{
  "nombre": "Alex",
  "rol": "miembro",
  "email": "oeepi@eale.com",
  "password": "123",
  "edad": 34,
  "ciudad": "Barcelona",
  "intereses": ["Padel", "Fauna"],
  "permiteRecibirOfertas": false
}
###

//ADMIN

POST http://localhost:3000/api/control/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDA2MjlmM2JjYjVjZjgyNTk4YTQ3NmQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NzgxMjU3NTAsImV4cCI6MTY3ODEzMjk1MH0.vQIpLoM67ss6kIdr8OBHiQJoko7LXOfHVcPtDMhw-TE

{
  "nombre": "Francisco",
  "rol":"admin",
  "email": "daddadafsfd@example.com",
  "password": "123",
  "edad": 34,
  "ciudad": "Barcelona",
  "intereses": ["Padel", "Fauna"],
  "permiteRecibirOfertas": true
}
###

PUT   http://localhost:3000/api/control/664dc52b05f94a0d3a8c499a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRkYzUyYjA1Zjk0YTBkM2E4YzQ5OWEiLCJpYXQiOjE3MTYzNzI3NzksImV4cCI6MTcxNjM3OTk3OX0.dQNV5xjJwmM6ymkSl9L_9z-3XrW9d3QsoIkaPYkTrXA

{
  "nombre": "Nuevo nombre",
  "email": "nueo@example.com",
  "password": "nuevacontraseña",
  "ciudad": "Nueva Ciudad",
  "intereses": ["música", "viajes"],
  "permiteRecibirOfertas": false
}
###

//ELIMINAR ADMINS DELETE

